module.exports = Object.freeze({
  UPDATE_SETTINGS: 'SORROWCORD_SETTINGS_UPDATE',
  TOGGLE_SETTING: 'SORROWCORD_SETTING_TOGGLE',
  UPDATE_SETTING: 'SORROWCORD_SETTING_UPDATE',
  DELETE_SETTING: 'SORROWCORD_SETTING_DELETE'
});
